# default values for all IOCs on bl19i
exports:
  beamline_defaults:
    beamline: bl19i
    # uncomment to force the service account, leave commented for namespace default
    # serviceAccount: bl19i-priv

    # NOTE: the following are all beamline defaults that can be overridden in
    # individual IOC values.yaml files.

    # for RTEMS IOCS this is the PVC name for the filesystem where RTEMS
    # IOCs look for their files - enable this in RTEMS IOCs only
    # nfsv2TftpClaim: bl19i-ioc-files-claim

    # provide a PVC for autosave
    autosave: true

    hostNetwork: true

    # useAffinity - when true, only run on nodes with label beamline:bl19i
    useAffinity: false

    # some beamline default resource limits
    resources:
      limits:
        cpu: "3"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 200Mi

    globalenv:
      # by default enable a liveness probe that checks ${IOC_PREFIX}:UPTIME
      - name: "K8S_IOC_LIVENESS_ENABLED"
        value: true

      # TODO - NOT YET REQUIRED ################################################
      #
      # In future these values could be used to auto configure an RTEMS
      # boot loader.
      #
      ##########################################################################
      # Where to find RTEMS IOC files - can be removed if you have no RTEMS
      - name: "K8S_IOC_TFTP_ADDR"
        value: "127.0.0.1"
      - name: "K8S_IOC_TFTP_PORT"
        value: "69"
      - name: "K8S_IOC_NFS_MOUNT"
        value: "127.0.0.1:iocs"
